import 'vue-awesome/icons/user'
import 'vue-awesome/icons/home'
import 'vue-awesome/icons/coins'
import 'vue-awesome/icons/paperclip'
import 'vue-awesome/icons/university'
import 'vue-awesome/icons/file-alt'
import 'vue-awesome/icons/calendar'
